apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUyT0RnME5EazJOVEFlRncweE9UQTVNVGd5TWpFMk1EVmFGdzB5T1RBNU1UVXlNakUyTURWYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUyT0RnME5EazJOVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk44ODV0Q29wNG5ocnZMME1lVmYvVnRaRW1Ib2lDTnBCQmd3Q2VUcUZPb3MKS2JzUDdmcWd4SnY2dC9WcDl5bUJvMnl3d2NOYy9jMlZodFl3dDQvQUtXcWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJ5OHlmQStkTEJwClFGS0hucmJ0RkRBbForNGJ1RjFndzJjcnF2UWNpMXpIQWlCK21XOWV1Z1ZwTzlXUmhVdlpzakhiQWJ2YXNNd24KWDIwMXVXdmptNGU3d3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.0.11:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 1c407bf321fe49952dd761fd2cd0377f
    username: admin
