# This is used to manage Ansible role dependences
# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# Install with: `ansible-galaxy install -r requirements.yml`

- name: k3s-server
  src: https://github.com/nemonik/k3s-server-role.git
  version: master

- name: metallb
  src: https://github.com/nemonik/metallb-role.git
  version: master

- name: traefik
  src: https://github.com/nemonik/traefik-role.git
  version: master

- name: docker-registry
  src: https://github.com/nemonik/docker-registry-role.git
  version: master
