---
# tasks file for openshift-cli

# Copyright (C) 2018 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: check if oc exists
  become: yes  
  stat:
    path: /usr/local/bin/oc
  register: oc
  tags:
    - openshift

- name: download and unpack openshift origin client tools
  become: yes  
  unarchive:
    src: "https://github.com/openshift/origin/releases/download/{{ openshift_origin_client_tools_version }}.tar.gz"
    dest: /usr/local/bin
    exclude:
      - README.md
      - LICENSE
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: oc.stat.exists == False
  tags:
    - openshift

# Remember:
# ./oc login https://192.168.0.11:8443 --insecure-skip-tls-verify=true