name: Basic role syntax check

on:
  push:
    branches:
      - master
    paths:
#      - 'ansible/roles/**'
#      - 'box/ansible/roles/**'

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=${PWD}/ansible/roles:${PWD}/box/ansible/roles' >ansible.cfg

      - name: Basic role syntax check
        run: | 
          paths=( "${PWD}/ansible/roles" "${PWD}/box/ansible/roles" )
          for path in "${paths[@]}"; do
            echo ${path}
            cd ${path}
            for role in `find . -maxdepth 1 -type d`; do
              if [ "$role" != "." ] && [ "$role" != ".." ]; then
                cd ${role}
                echo $PWD
                ls -las
                ansible-playbook tests/test.yml -i tests/inventory --syntax-check
              fi
            done
          done 
